page:
    type:       rest
    resource:   WikiBundle\Controller\PageController

page_revision:
    type:       rest
    parent:     page
    resource:   WikiBundle\Controller\RevisionController

status:
    type:       rest
    resource:   WikiBundle\Controller\StatusController


category:
    type:       rest
    resource:   WikiBundle\Controller\CategoryController

security:
    type:       rest
    resource:   WikiBundle\Controller\SecurityController