page:
    type:       rest
    resource:   WikiBundle\Controller\PageController

page_revision:
    type:       rest
    parent:     page
    resource:   WikiBundle\Controller\RevisionController

status:
    type:       rest
    resource:   WikiBundle\Controller\StatusController

rating:
    type:       rest
    resource:   WikiBundle\Controller\RatingController

category:
    type:       rest
    resource:   WikiBundle\Controller\CategoryController

comment:
    type:       rest
    resource:   WikiBundle\Controller\CommentController

security:
    type:       rest
    resource:   WikiBundle\Controller\SecurityController