<?php

namespace WikiBundle\Repository;

/**
 * PageRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

	public function searchCommentsWithOffsetAndLimit($page, $offset, $limit){
        $query = $this->createQueryBuilder('c')
                      ->andWhere('c.page = :page')
                      ->orderBy('c.createdAt', 'DESC')
                      ->setParameter('page', $page);
        if ($offset != "") {
            $query->setFirstResult($offset);
        }
        if ($limit != "") {
            $query->setMaxResults($limit);
        }
        return $query->getQuery()->getResult();
	}
}
