<?php

namespace WikiBundle\Repository;

/**
 * ContentImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentImageRepository extends \Doctrine\ORM\EntityRepository
{
}
