<?php

namespace WikiBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPagesByCategoryWithOffsetAndLimit($category, $offset, $limit){
        $query = $this->createQueryBuilder('p')
                      ->where('p.category = :category')
                      ->setParameter('category', $category)
                      ->orderBy('p.id', 'ASC');
        if ($offset != "") {
            $query->setFirstResult($offset);
        }
        if ($limit != "") {
            $query->setMaxResults($limit);
        }
        return $query->getQuery()->getResult();
	}

  public function getTopPages(){
    $query = $this->createQueryBuilder('p')
                      ->select('p.id as page_id, p.viewCount, MAX(r.id) as rev_id, r.title')
                      ->innerJoin('p.revisions', 'r')
                      ->groupBy('p.id')
                      ->orderBy('p.viewCount', 'DESC')
                      ->setMaxResults(10);
        return $query->getQuery()->getArrayResult();
  }
}
