# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.exception_listener:
        class: WikiBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 15 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 15 }

    wiki.counter.counter_view:
        class: WikiBundle\Counter\CounterViewPage
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']
    wiki.rating_manager:
        class: WikiBundle\Rating\RatingManager
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
    wiki.file_uploader:
        class: WikiBundle\Service\FileUploader
        arguments: ['%upload_path_banner%']